name: disaster-response-pipeline-project

# Disable key loading - https://docs.lando.dev/config/ssh.html#customizing
keys: false

services:
  python:
    type: python:3.11.5
    build:
      - 'sh -c build/build.sh'
    run:
      - 'sh -c build/start.sh'

tooling:
  pip:
    service: python
  python:
    service: python